# This is a generated file by dfetch. Don't edit this, but edit the manifest.
# For more info see https://dfetch.rtfd.io/en/latest/getting_started.html
dfetch:
  branch: scarthgap
  hash: 1ef00d1372c4f8c0a9c0f1f93ac82aff
  last_fetch: 21/02/2026, 16:55:40
  patch: ''
  remote_url: https://git.yoctoproject.org/meta-raspberrypi
  revision: 2c646d29912dcc873469a57b1c207e1549c5094d
  tag: ''
